services:

  internal:
    image:  ghcr.io/samitkumarpatel/hello-cloud-backend:main
    networks:
      - hello-cloud

  external:
    image: ghcr.io/samitkumarpatel/hello-cloud-fe:main
    ports:
      - published: 8080
        target: 8080
        mode: host
    environment:
      INTERNAL_API_HOST: http://internal:8081
    networks:
      - hello-cloud

networks:
  hello-cloud:
