spring:
  application:
    name: hello-cloud-backend
  webflux:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 8081
